// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetBrowser(arg1) {
  return window['go']['main']['App']['SetBrowser'](arg1);
}
